baseURL = "/"
defaultContentLanguage = "nl"
languageCode = "nl-nl"
title = "Gerton"
MetaDataFormat = "toml"
canonifyurls = true
paginate = 5
theme = "kuhn"
copyright = "copyright 2018 Gerton ten Ham"
enableRobotsTXT = true

[author]
  name = "Gerton ten Ham"

[params]
  DateForm = "Jan 2, 2006"
  Description = "Just some thoughts, nothing else..."
  Author = "Gerton ten Ham"
  postSummariesFrontPage = 5 #Number of post summaries to show on front page, comment out to allow default(4)
  customCssPath = "css/custom.css"
  logo = "/img/logo.png"

[[params.social]]
  title = "github"
  url = "https://github.com/gtenham"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/gerton.tenham"
[[params.social]]
  title = "linkedin"
  url = "https://www.linkedin.com/in/gertontenham/"

[[menu.main]]
  name = "blog"
  url = "/"
  weight = -200
[[menu.main]]
  name = "over mij"
  url = "/over-mij/"
  weight = -180
#[[menu.main]]
#  name = "contact"
#  url = "/contact/"
#  weight = -160
[[menu.main]]
  name = "archief"
  url = "/articles/"
  weight = -140